### PR TITLE
Hatari 2.0 merged with r-type/hatari + CFG file selection from CLI

### PR DESCRIPTION
**Pull request by RetroUp**
Hatari 2.0 merged with https://github.com/r-type/hatari + CFG file
selection from CLI

Important:
Load CFG file instead of STX. Example CFG's are in the etc folder.
example:
retroarch.exe -L cores\hatari_libretro.dll "content\st\cfg\9 Lives.cfg"

### CODE REVIEW

**Comment by r-type** [comment]
Nice works but i really don't like the idea to merge a big commit that include all change done in upstream since.and loose all upstream commits.

The things to do is to

 1) rebase first to the last version based on hatari mercurial. and then keeping  the upstream commits
 2) reapply libretro surface patch
 3) apply your cfg file selection.

**Comment by r-type** [comment]
for starting point, i import the last hatari source here https://github.com/r-type/hatari2

**Comment by RetroUp** [comment]
Thanks. I applied my changes to your version - search system dir instead of root and easily load config files. If you accept the changes then the hatari info file should be updated as well.

You are probably aware, but your version is currently not compiling.

**Comment by r-type** [comment]
> You are probably aware, but your version is currently not compiling.
witch OS , , for now it build fine on linux and emscripten the rest not tested.

**Comment by r-type** [comment]
ok you talk about new core , yes it's broken i ll look at .
for now only the old cpu compile fine.

**Comment by RetroUp** [comment]
Compiling on Windows. I was talking about your 2.0 version. I think I tried both with and without new core but not 100% positive.

This 2.0 version that I made from your 1.9 is compiling on Windows but is missing many of your changes.

**Comment by r-type** [comment]
Strange, I've tested on windows , now they compiling fine (old and new) .
and old cpu works fine , but the new one crash after some frame.

**Comment by r-type** [comment]
For newcpu core,due to libco usage ,  on windows it works fine if compiled with an sjlj toolchain (or if forcing to use fibers instead amd64 in libco) like mame .
But they definitively compile fine .

**Comment by RetroUp** [comment]
Worked this time. Thanks.

**Pull request closed without merging**
